name: Publish main package

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  deploy:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Build package
      run: poetry build -f wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
