name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Run tests
      run: make test
    - name: Install visualization package dependencies
      run: |
        cd argo_workflow_tools_visualization/
        make install-ubuntu
    - name: Run visualization package tests
      run: |
        cd argo_workflow_tools_visualization/
        poetry run make test
